name: Release Image

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to release'
        required: true

env:
  NODE_AGENT_CONTAINER_NAME: node-agent
  REGISTRY_HOST: registry.cn-hangzhou.aliyuncs.com
  REGISTRY_USERNAME_ARM: originx

jobs:
  build-images:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: ubuntu-latest
            arch: amd64
    runs-on: ${{ matrix.os }}
    outputs:
      IMAGE_TAG_NAME: ${{ steps.build-images.outputs.IMAGE_TAG_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca

      - name: Log in to container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Generate image metadata
        id: build-image
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_NAME: ${{ github.sha }}
        run: |
          echo "IMAGE_TAG_NAME=${{ github.event.inputs.tag }}" >> "$GITHUB_OUTPUT"
          echo "NODE_AGENT_IMAGE_FULL_TAG=${{ env.REGISTRY_HOST }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.NODE_AGENT_CONTAINER_NAME }}:${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          echo "NODE_AGENT_IMAGE_FULL_TAG_ARM=${{ env.REGISTRY_HOST }}/${{ env.REGISTRY_USERNAME_ARM }}/${{ env.NODE_AGENT_CONTAINER_NAME }}:${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Build node-agent docker image and push
        run: |
          make docker-build ORG="${{ env.REGISTRY_HOST }}/${{ secrets.REGISTRY_USERNAME }}" TAG="${{ github.event.inputs.tag }}"
          docker push ${{ env.NODE_AGENT_IMAGE_FULL_TAG }}

      - name: Build node-agent docker image and push(ARM64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ env.NODE_AGENT_IMAGE_FULL_TAG_ARM }}

      - name: push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ github.event.inputs.tag }}
